# Setup
name:         Slimme peuter project
tagline:      Een site met informatie en ideeën voor de begeleiding van peuters met een ontwikkelingsvoorsprong, gericht op pedagogisch medewerkers van kinderopvangcentra.
baseurl:      ""

# Plugins do not work in GitHub
#plugins:
#  - jekyll-paginate

#Others
markdown: kramdown
