# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Slimme Peuter Project
email: info@slimmepeuterproject.nl
description: Een site met informatie en ideeën voor de begeleiding van peuters met een ontwikkelingsvoorsprong, gericht op pedagogisch medewerkers van kinderopvangcentra.
baseurl: ""
url: "https://slimmepeuterproject.nl"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
